name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Khi bạn push lên nhánh main thì GitHub sẽ tự động build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.2'  # Phiên bản bạn đang dùng
          extended: true

      - name: Build website
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
